export const GIGIPAY_ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'EmptyArray', type: 'error' },
  { inputs: [], name: 'EnforcedPause', type: 'error' },
  { inputs: [], name: 'IncorrectNativeAmount', type: 'error' },
  { inputs: [], name: 'InsufficientAllowance', type: 'error' },
  { inputs: [], name: 'InvalidAmount', type: 'error' },
  { inputs: [], name: 'InvalidClaimCode', type: 'error' },
  { inputs: [], name: 'InvalidExpirationTime', type: 'error' },
  { inputs: [], name: 'InvalidRecipient', type: 'error' },
  { inputs: [], name: 'InvalidRecipientHash', type: 'error' },
  { inputs: [], name: 'InvalidServiceId', type: 'error' },
  { inputs: [], name: 'InvalidServiceType', type: 'error' },
  { inputs: [], name: 'LengthMismatch', type: 'error' },
  { inputs: [], name: 'TransferFailed', type: 'error' },
  { inputs: [], name: 'VoucherAlreadyClaimed', type: 'error' },
  { inputs: [], name: 'VoucherAlreadyRefunded', type: 'error' },
  { inputs: [], name: 'VoucherExpired', type: 'error' },
  { inputs: [], name: 'VoucherNotExpired', type: 'error' },
  { inputs: [], name: 'VoucherNotFound', type: 'error' },
  {
    inputs: [
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'address[]', name: 'recipients', type: 'address[]' },
      { internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
    ],
    name: 'batchTransfer',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'voucherName', type: 'string' },
      { internalType: 'string', name: 'claimCode', type: 'string' },
    ],
    name: 'claimVoucher',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'string', name: 'voucherName', type: 'string' },
      { internalType: 'string[]', name: 'claimCodes', type: 'string[]' },
      { internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'expirationTimes', type: 'uint256[]' },
    ],
    name: 'createVoucherBatch',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'sender', type: 'address' }],
    name: 'getSenderVouchers',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: 'voucherName', type: 'string' }],
    name: 'getVouchersByName',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: 'voucherName', type: 'string' }],
    name: 'refundVouchersByName',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'voucherId', type: 'uint256' }],
    name: 'isVoucherClaimable',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'voucherId', type: 'uint256' }],
    name: 'isVoucherRefundable',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'vouchers',
    outputs: [
      { internalType: 'address', name: 'sender', type: 'address' },
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'bytes32', name: 'claimCodeHash', type: 'bytes32' },
      { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
      { internalType: 'bool', name: 'claimed', type: 'bool' },
      { internalType: 'bool', name: 'refunded', type: 'bool' },
      { internalType: 'string', name: 'voucherName', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
  {
    inputs: [
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'string', name: 'serviceType', type: 'string' },
      { internalType: 'string', name: 'serviceId', type: 'string' },
      { internalType: 'bytes32', name: 'recipientHash', type: 'bytes32' },
    ],
    name: 'payBill',
    outputs: [{ internalType: 'uint256', name: 'orderId', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'withdrawBillFunds',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
